services:
  backend:
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/quiz_app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz_app
    volumes:
      - data:/var/lib/postgresql/data

  adminer: # To view database. This is for debugging/presentation.
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  data:
